FROM gentoo/portage:latest AS portage
FROM gentoo/stage3:latest

COPY --from=portage /var/db/repos/gentoo /var/db/repos/gentoo

# Portage config (sandbox disabled because all ebuilds use RESTRICT="network-sandbox")
RUN echo 'FEATURES="-network-sandbox -ipc-sandbox -pid-sandbox"' >> /etc/portage/make.conf && \
    echo 'ACCEPT_KEYWORDS="~amd64"' >> /etc/portage/make.conf && \
    echo 'ACCEPT_LICENSE="*"' >> /etc/portage/make.conf && \
    echo 'RUBY_TARGETS="ruby32 ruby33"' >> /etc/portage/make.conf && \
    echo 'USE="X icu opengl harfbuzz"' >> /etc/portage/make.conf && \
    mkdir -p /etc/portage/package.mask && \
    echo '>=dev-lang/ruby-3.4' > /etc/portage/package.mask/ruby

# pkgcheck installed BEFORE COPY overlay to benefit from Docker cache
RUN emerge --quiet --noreplace dev-util/pkgcheck

# repos.conf config for the overlay
RUN mkdir -p /etc/portage/repos.conf && \
    cp /usr/share/portage/config/repos.conf /etc/portage/repos.conf/gentoo.conf && \
    printf '[diodonfrost]\nlocation = /var/db/repos/diodonfrost\n' \
    > /etc/portage/repos.conf/diodonfrost.conf

# Copy overlay (only layer invalidated on each change)
COPY . /var/db/repos/diodonfrost

# Generate Manifests (source tarball checksums)
RUN for ebuild in $(find /var/db/repos/diodonfrost -name '*.ebuild'); do \
        ebuild "${ebuild}" manifest; \
    done

WORKDIR /var/db/repos/diodonfrost
